
main_dir_name: DesktopSort
main_dir_path: C:\Users\Louis\Desktop
unsorted_dir_name: Dump

Sort_Desktop: True
sort_Downloads: True

directories: {
            Movies: [
                      .mp4,
                      .mov,
                      .avi,
                      ],

            Document: [
                    .pdf,
                    .txt,
                    ],

            Images: [
                    .JPG,
                    .jpg,
                    .png,
                    ],

            Music: [
                   .mp3,
                  ],
            programs: [
                  .exe,
                  .msi
                  ],

            Houdini: [
                  .hip,
                  .hipnc,            
                  ],
            Blender: [
                  .blend,
            ],

            Zip_Files: [
                  .zip,
                  .rar,
                  ],
              }

